var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};require("date-utils");
var LOGGER_LEVELS={silly:0,debug:1,verbose:2,info:3,warn:4,error:5},fs=require("fs"),morgan=require("morgan"),winston=require("winston"),moment=require("moment"),urlencode=require("urlencode"),dailyFile=require("winston-daily-rotate-file"),makeDir=require("./makeDir"),middlewares={},container=null,defaultLogger=null;
(function(a){container=new winston.Container({level:a.level||"silly",json:a.json||!1,colorize:a.colorize||!1,handleExceptions:!0});defaultLogger=container.add("default",{transports:[new winston.transports.Console({level:a.level||"silly",name:"default-logger"})]});defaultLogger.level=a.level||"silly"})({});function formatSetting(a){return function(b){var c=a,c=c.replace(":msg",b.message),c=c.replace(":level",b.level.toUpperCase());return c=c.replace(":time",b.timestamp())}}
function makeMiddleware(a,b){var c=morgan.compile(a);return function(a,e,f){container.get(b).info(urlencode.decode(c(morgan,a,e)));f()}}
function makeTransports(a,b){var c=[];!b&&a.transport&&"consonle"!==a.transport||c.push(new winston.transports.Console({level:a.level,colorize:a.colorize||!1,formatter:formatSetting(a.format),timestamp:function(){return moment().format(a.timestamp||"HH:mm:ss")}}));"file"===a.transport&&c.push(new dailyFile({level:a.level,colorize:a.colorize||!1,json:!1,formatter:formatSetting(a.format),dirname:makeDir(a.name,a.filePath),datePattern:a.datePattern,filename:a.fileName,timestamp:function(){return moment().format(a.timestamp||
"HH:mm:ss")}}));return c}
function setup(){var a,b,c;c=Array.prototype.slice.call(arguments);a="string"===typeof c[0]?c.shift():null;c="object"===typeof c[0]?c.shift():null;console.log("[Logger] setup File Path ==> "+a);console.log("[Logger] setup options ==> "+JSON.stringify(c));if(a){a=JSON.parse(fs.readFileSync(a,"utf8"));console.log("[Logger] Config ==> "+JSON.stringify(a));if(a.loggers&&Array.isArray(a.loggers)){var d=$jscomp.makeIterator(a.loggers);for(b=d.next();!b.done;b=d.next())b=b.value,console.log("[Logger] Create Logger ==> "+
JSON.stringify(b)),container.add(b.name,{transports:makeTransports(b,a.rootLogger===b.name&&"debug"===process.env.NODE_ENV)}),container.get(b.name).level=b.level||"debug"}if(a.middlewares&&Array.isArray(a.middlewares))for(d=$jscomp.makeIterator(a.middlewares),b=d.next();!b.done;b=d.next())b=b.value,middlewares[b.name]=makeMiddleware(b.format,b.logger);a.rootLogger&&(defaultLogger=container.get(a.rootLogger))}c&&init();return main}var getMiddleware=function(a){return middlewares[a]};
function makeFunc(a){return function(){for(var b="",c=Array.prototype.slice.call(arguments),d=this.name&&container.has(this.name)?container.get(this.name):defaultLogger,e=0;e<c.length;e++)if("object"===typeof c[e])try{b=c[e].toString(),0<=b.indexOf("[object Object]")&&(b=JSON.stringify(c[e])),c[e]=b}catch(f){c[e]="[Unknown Object]"}d&&LOGGER_LEVELS[a]>=LOGGER_LEVELS[d.level]&&LOGGER_LEVELS[a]>=LOGGER_LEVELS[container.options.level]&&d[a].apply(d,c)}}
var getLogger=function(a){var b=Object.create(defaultLogger),c=null;b.name=a;for(c in LOGGER_LEVELS)b[c]=makeFunc(c);return b},main=module.exports=setup;main.setup=setup;main.getMiddleware=getMiddleware;main.getLogger=getLogger;